### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by fgeoffroy** [fgeoffroy/YanivOnline#1]
POur la partie serveur. Django channels ou alors un truc plus classique comme socket.io ?

**Comment by jfouret** [comment]
# Proposal

## Architecture

Front-end : HTML jinja template
Web serveur : Django
Database : SQLite
Backend : Python function that might interact with SQLlite DB

## What to do 

### Database schema

Create an SQL schematic that contains information about
* Credentials to connect to the servers
* information about a game
  * type of game
  * Id of game and credential
    * Players informations
    * ID
    * Credential
    * Display Name
    * Hand (NB: pickle module can be used to store directly python object into binary format)
  * status of the game
    * Deck
    * Turn
    * Players
    * Initiative which player have the initiative ?

### Webserver

Create several views/url
* Login to the server
* Join/create a game
* Game view

### Front-end

* For the game view : An HTML/js front-end usig jinja2 will be used as template by python back-end functions
* For other views : simple forms 

We can search internet to find good templates !

### back end

Python back-end functions must be designed to interact with views

**Comment by jfouret** [comment]
Pour info, un projet similaire mais en GO :https://github.com/yanc0/goyaniv
