### ISSUE TITLE
UTF8

### ISSUE THREAD

**Issue by fgeoffroy** [fgeoffroy/YanivOnline#9]
How do we make sure that the user names and room names given in the form are UTF8 ?
It is important for stocking information in the database

**Comment by jfouret** [comment]
Somme key in settings.py that might be part of the answer:
https://docs.djangoproject.com/fr/3.0/ref/settings/#charset
https://docs.djangoproject.com/fr/3.0/ref/settings/#default-charset

As far as I understood it. Default results from httpresponse are unicode, it need to be encoded with utf-8. with .encode(codec) method.

It should be managed internally by django and default charset setting should be utf-8.

However I read that if the system terminal that runs the server is using ASCII, it may be possible that ASCII is defined as the  default charset.

> TODO: check terminal encoding

**Comment by jfouret** [comment]
```
$ docker run -it django
root@a79e81a9e62b:/# python -c "import sys; print(sys.stdout.encoding)"
utf-8
```

**Comment by fgeoffroy** [comment]
Solved with RegexValidator in Django
